### ISSUE TITLE
Convert panics to crashes

### ISSUE THREAD

**Issue by kmcallister** [kmcallister/afl.rs#1]
So that afl can detect them. This should be optional, because sometimes we're only interested in memory corruption and not "benign" panics.

See also what [python-afl](https://bitbucket.org/jwilk/python-afl/src/default/afl.pyx?at=default) does.

**Comment by cmr** [comment]
If you're ok with modifying the binary being run, you can use http://static.rust-lang.org/doc/master/std/rt/unwind/fn.register.html.

**Comment by kmcallister** [comment]
Nice! afl already involves a compiler plugin and a small runtime library. I can integrate the unwind hook into the existing init code.

**Comment by Manishearth** [comment]
This could also be done by overriding the `panic_fmt` lang item or whatever it's called; but register seems better.
