### ISSUE TITLE
Recommend --release ?

### ISSUE THREAD

**Issue by frewsxcv** [kmcallister/afl.rs#4]
When running alf.rs using a Rust project build using `cargo build` I get 1600 execs / second. If I do `cargo build --release` I get around 1900 execs / second. Maybe we should be recommending `--release`?

**Comment by frewsxcv** [comment]
I take this back. I'm worries `--release` will optimize out important logic that should be tested.

**Comment by mgeisler** [comment]
I would like to ask about this as well: it would be great if the documentation could contain a section on what the impact of `--release` would be. Should I avoid it or should I include it?

I notice that `cargo fuzz` will build the fuzz target in release mode by default, so perhaps it's okay? If it's okay, could `cargo afl build` default to use `--release` as well?

**Comment by smoelius** [comment]
Hi, @mgeisler.

> Should I avoid it or should I include it?

Generally speaking, I don't think it should make a difference. Here are the settings that can be controlled in a profile: https://doc.rust-lang.org/cargo/reference/profiles.html#profile-settings

But as you can see, most of them are set in afl.rs's source code: https://github.com/rust-fuzz/afl.rs/blob/8cc6467f5a50d1ef5c5ead6f7b92e95a48372673/src/bin/cargo-afl.rs#L322-L331

I suspect that [@frewsxcv's comment](https://github.com/rust-fuzz/afl.rs/issues/4#issuecomment-101093285) was in regard to things like `debug-assertions` and `overflow-checks`. By default, these are [disabled in a release build](https://doc.rust-lang.org/cargo/reference/profiles.html#release).

**Comment by mgeisler** [comment]
Hi @smoelius, thank you, that's very helpful information! I'm sorry for not replying earlier, I missed your reply.

**Comment by smoelius** [comment]
No problem. I barely remember writing this, TBH. :laughing:
